### ISSUE TITLE
DNS service stopping randomly and repeatedly

### ISSUE THREAD

**Issue by BlackScreen** [pi-hole/FTL#1118]
### Versions
- Pi-hole: v5.3.1
- AdminLTE: v5.5
- FTL: v5.8

### Platform
- OS and version: Raspbian GNU/Linux 10 (buster)
- Platform: Raspberry Pi 4

### Expected behavior
DNS service should not stop unexpectedly

### Actual behavior / bug
It is the third day, that the DNS service is stopping unexpectedly, without any reason why.
It happens in the morning (at about 9 to 10 am), when I run `pihole status` it says:
`[✗] DNS service is NOT listening`
I can fix it by entering `pihole restartdns` - output: `[✓] Restarting DNS server`
Please fix this bug as soon as possible, it is really annoying.

### Steps to reproduce
Letting pi-hole run on my Raspberry Pi, wait and then it stops. This happened never before, only after the last update.

### Debug Token
- URL: https://tricorder.pi-hole.net/r147kspayd

**Comment by dschaper** [comment]
> Same problem here.

Possibly, can't really tell since you've provided nothing that we can review to see.

**Comment by DrNoCDN** [comment]
I've re-deployed my docker-pi-hole on v5.6 tag (and set it to static) and it seems stable.. I now wish I hadn't have been using watchtower (now removed) and/or set my critical DNS services tagged to latest build... lesson learned :)

**Comment by rafale77** [comment]
> > Same problem here.
> 
> Possibly, can't really tell since you've provided nothing that we can review to see.

What would you like me to provide? I am reporting exactly the same symptom as @BlackScreen with exactly the same restart procedure.

**Comment by dschaper** [comment]
Okay, I'll count that as a +1 then and try to solve BlackScreen's issue. If it also works for you then bonus I guess.

**Comment by rafale77** [comment]
I dug into my FTL logs and found the same thing you did. I am now testing the development branch. I first had to wipe my FTL database as it was locked. Seems to have stopped the SQL3 errors.

**Comment by kirmandi** [comment]
also have the issue of crashing FTL/DNS with dashboard showing "unable to connect to API"

the FTL logs includes the following:
```
[2021-04-21 08:26:00.904 1405/T1409] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
[2021-04-21 08:26:00.904 1405/T1409] SQLite3 message: database disk image is malformed in "DELETE FROM network_addresses WHERE lastSeen < 1587450360;" (11)
[2021-04-21 08:26:00.905 1405/T1409] ERROR: SQL query "DELETE FROM network_addresses WHERE lastSeen < 1587450360;" failed: database disk image is malformed
[2021-04-21 08:26:00.906 1405/T1409] SQLite3 message: API call with invalid database connection pointer (21)
[2021-04-21 08:26:00.907 1405/T1409] SQLite3 message: misuse at line 165242 of [5d4c65779d] (21)
[2021-04-21 08:26:00.907 1405/T1409] Error while trying to close database: bad parameter or other API misuse
```

only restarting DNS helps to fix this temporarily so far. but a lot of SQLite3 malformed and bad database message directly re-appear.

would cleaning the database file be worth a try?
or will there be a new (hotfix) release soon, if there is already a fix on `development` branch? 
it's rather inconvenient if the DNS just starts failing randomly throughout the day.

**Comment by rafale77** [comment]
After validating for a few hours, I am pretty confident that it is fixed in the the development branch. I am pretty sure it will be in a hotfix release soon.

**Comment by john2691** [comment]
Development branch build seems to be working for me as well, no DNS failure overnight.

**Comment by john2691** [comment]
Scratch that, it went down again about an hour ago. Log at https://tricorder.pi-hole.net/iicgm776iw, though this is the log after it came back online.

**Comment by DL6ER** [comment]
@BlackScreen 

> kept in sync by gravity sync

We've seen a few reports on our Discourse forum that gravity sync is causing issues. Once the user removed it, FTL stopped going down. I don't really recall what happened but it seem to recall it having to do something with stopping but never restarting FTL.

This also matches your debug log

    [2021-04-20 10:00:12.810 1211M] Shutting down...
    [...]
    [2021-04-20 10:00:13.119 1211M] ########## FTL terminated after 23h 47m 44s  (code 0)! ##########
    [2021-04-20 10:07:26.903 13872M] Using log file /var/log/pihole-FTL.log
    [2021-04-20 10:07:26.903 13872M] ########## FTL started! ##########
    [...]

where you can see that FTL was stut down **by something/-one** at some point (it worked properly before) and was (probably manually?) restarted only about 7 minutes later.

There isn't enough information to give specific hints for the others in this thread, but I should say that the database does not need to be deleted to remove the lock. When the database is still locked after FTL is shut down, then there is some other process keeping a lock on the file. Deleting the database will obviously also unlock it, but that does not sound like the proper solution.

**Comment by dschaper** [comment]
> 
> 
> Scratch that, it went down again about an hour ago. Log at https://tricorder.pi-hole.net/iicgm776iw, though this is the log after it came back online.

```plain
   [2021-04-21 12:49:58.188 29905M] getIfaceFromIP("::1") - SQL error prepare: database disk image is malformed
   [2021-04-21 12:49:58.189 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
   [2021-04-21 12:49:58.189 29905M] SQLite3 message: database disk image is malformed in "SELECT aliasclient_id FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? AND aliasclient_id IS NOT NULL GROUP BY ip HAVING max(lastSeen));" (11)
   [2021-04-21 12:49:58.189 29905M] getAliasclientIDfromIP("::1") - SQL error prepare: database disk image is malformed
   [2021-04-21 12:49:58.252 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
   [2021-04-21 12:49:58.252 29905M] SQLite3 message: database disk image is malformed in "SELECT hwaddr FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? GROUP BY ip HAVING max(lastSeen));" (11)
   [2021-04-21 12:49:58.252 29905M] getMACfromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
   [2021-04-21 12:49:58.252 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
   [2021-04-21 12:49:58.252 29905M] SQLite3 message: database disk image is malformed in "SELECT name FROM network_addresses WHERE name IS NOT NULL AND ip = ?;" (11)
   [2021-04-21 12:49:58.252 29905M] getNameFromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
   [2021-04-21 12:49:58.253 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
   [2021-04-21 12:49:58.253 29905M] SQLite3 message: database disk image is malformed in "SELECT interface FROM network JOIN network_addresses ON network_addresses.network_id = network.id WHERE network_addresses.ip = ? AND interface != 'N/A' AND interface IS NOT (11)
   [2021-04-21 12:49:58.253 29905M] getIfaceFromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
   [2021-04-21 12:49:58.254 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
   [2021-04-21 12:49:58.254 29905M] SQLite3 message: database disk image is malformed in "SELECT aliasclient_id FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? AND aliasclient_id IS NOT NULL GROUP BY ip HAVING max(lastSeen));" (11)
   [2021-04-21 12:49:58.254 29905M] getAliasclientIDfromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
   [2021-04-21 12:50:00.896 29905/T29909] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
   [2021-04-21 12:50:00.896 29905/T29909] SQLite3 message: database disk image is malformed in "DELETE FROM network_addresses WHERE lastSeen < 1587491400;" (11)
   [2021-04-21 12:50:00.897 29905/T29909] ERROR: SQL query "DELETE FROM network_addresses WHERE lastSeen < 1587491400;" failed: database disk image is malformed
   [2021-04-21 12:50:00.897 29905/T29909] SQLite3 message: API call with invalid database connection pointer (21)
   [2021-04-21 12:50:00.897 29905/T29909] SQLite3 message: misuse at line 165242 of [5d4c65779d] (21)
   [2021-04-21 12:50:00.897 29905/T29909] Error while trying to close database: bad parameter or other API misuse
```

Did you delete the database prior to changing to the `development` FTL version or is this the same database that you've been running for a while?

**Comment by john2691** [comment]
> > Scratch that, it went down again about an hour ago. Log at https://tricorder.pi-hole.net/iicgm776iw, though this is the log after it came back online.
> 
> ```
>    [2021-04-21 00:05:00.892 770/T774] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 00:05:00.892 770/T774] SQLite3 message: database disk image is malformed in "DELETE FROM network_addresses WHERE lastSeen < 1587445500;" (11)
>    [2021-04-21 00:05:00.892 770/T774] ERROR: SQL query "DELETE FROM network_addresses WHERE lastSeen < 1587445500;" failed: database disk image is malformed
>    [2021-04-21 00:05:00.892 770/T774] SQLite3 message: API call with invalid database connection pointer (21)
>    [2021-04-21 00:05:00.892 770/T774] SQLite3 message: misuse at line 165242 of [5d4c65779d] (21)
>    [2021-04-21 00:05:00.892 770/T774] Error while trying to close database: bad parameter or other API misuse
>    [2021-04-21 00:06:00.978 770/T774] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 00:06:00.979 770/T774] SQLite3 message: database disk image is malformed in "DELETE FROM network_addresses WHERE lastSeen < 1587445560;" (11)
>    [2021-04-21 00:06:00.979 770/T774] ERROR: SQL query "DELETE FROM network_addresses WHERE lastSeen < 1587445560;" failed: database disk image is malformed
>    [2021-04-21 00:06:00.979 770/T774] SQLite3 message: API call with invalid database connection pointer (21)
> 
> ...
> 
>    [2021-04-21 12:49:58.188 29905M] getIfaceFromIP("::1") - SQL error prepare: database disk image is malformed
>    [2021-04-21 12:49:58.189 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 12:49:58.189 29905M] SQLite3 message: database disk image is malformed in "SELECT aliasclient_id FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? AND aliasclient_id IS NOT NULL GROUP BY ip HAVING max(lastSeen));" (11)
>    [2021-04-21 12:49:58.189 29905M] getAliasclientIDfromIP("::1") - SQL error prepare: database disk image is malformed
>    [2021-04-21 12:49:58.252 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 12:49:58.252 29905M] SQLite3 message: database disk image is malformed in "SELECT hwaddr FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? GROUP BY ip HAVING max(lastSeen));" (11)
>    [2021-04-21 12:49:58.252 29905M] getMACfromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
>    [2021-04-21 12:49:58.252 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 12:49:58.252 29905M] SQLite3 message: database disk image is malformed in "SELECT name FROM network_addresses WHERE name IS NOT NULL AND ip = ?;" (11)
>    [2021-04-21 12:49:58.252 29905M] getNameFromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
>    [2021-04-21 12:49:58.253 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 12:49:58.253 29905M] SQLite3 message: database disk image is malformed in "SELECT interface FROM network JOIN network_addresses ON network_addresses.network_id = network.id WHERE network_addresses.ip = ? AND interface != 'N/A' AND interface IS NOT (11)
>    [2021-04-21 12:49:58.253 29905M] getIfaceFromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
>    [2021-04-21 12:49:58.254 29905M] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 12:49:58.254 29905M] SQLite3 message: database disk image is malformed in "SELECT aliasclient_id FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? AND aliasclient_id IS NOT NULL GROUP BY ip HAVING max(lastSeen));" (11)
>    [2021-04-21 12:49:58.254 29905M] getAliasclientIDfromIP("fd98:dea2:cd5c:2:b6:fcb8:6f7:7186") - SQL error prepare: database disk image is malformed
>    [2021-04-21 12:50:00.896 29905/T29909] SQLite3 message: database corruption at line 68176 of [5d4c65779d] (11)
>    [2021-04-21 12:50:00.896 29905/T29909] SQLite3 message: database disk image is malformed in "DELETE FROM network_addresses WHERE lastSeen < 1587491400;" (11)
>    [2021-04-21 12:50:00.897 29905/T29909] ERROR: SQL query "DELETE FROM network_addresses WHERE lastSeen < 1587491400;" failed: database disk image is malformed
>    [2021-04-21 12:50:00.897 29905/T29909] SQLite3 message: API call with invalid database connection pointer (21)
>    [2021-04-21 12:50:00.897 29905/T29909] SQLite3 message: misuse at line 165242 of [5d4c65779d] (21)
>    [2021-04-21 12:50:00.897 29905/T29909] Error while trying to close database: bad parameter or other API misuse
> ```
> 
> Did you delete the database prior to changing to the `development` FTL version or is this the same database that you've been running for a while?

Same database, are there instructions on clearing the database?

**Comment by dschaper** [comment]
> Same database, are there instructions on clearing the database?

Yes, it's a sqlite3 file so you can `mv` it to a `.bak` if you'd like, else just `rm` it. `/etc/pihole/pihole-FTL.db`

**Comment by rafale77** [comment]
I have not had any issues since yesterday and indeed had to wipe my database to get rid of errant remaining database issues due to entries being locked.

**Comment by john2691** [comment]
@dschaper Done, will keep you updated.

**Comment by dschaper** [comment]
We've pushed the hotfix out so you should be able to go back to master.

If you ran `pihole checkout` then do it again with `pihole checkout ftl master` to get on the general release version.

**Comment by rafale77** [comment]
Gratitude! Just upgraded to 5.8.1. Thanks for the quick turnaround.

**Comment by john2691** [comment]
Back on the master branch, no SQL errors and everything seems to be fine.

**Comment by BlackScreen** [comment]
> We've seen a few reports on our Discourse forum that gravity sync is causing issues. Once the user removed it, FTL stopped going down. I don't really recall what happened but it seem to recall it having to do something with stopping but never restarting FTL.

@DL6ER 
Thanks for your tip. I will check this out, if the problem still occurs.
Today there was no problem. I updated to the latest FTP version, maybe this fixes it.

**Comment by kirmandi** [comment]
v5.8.1 seems to have fixed it for me, however i also reset the database by deleting it, as the malformed errors in log still occurred constantly ...

**Comment by BlackScreen** [comment]
I have not had a problem since Tuesday morning, when I opened this thread.
Hopefully and probably the problem is gone.

**Comment by BlackScreen** [comment]
Yeah, well... It happened again just now. Here are the logs of my two Pis:

1st Pi - before restartdns
https://tricorder.pi-hole.net/ts7ot0q1mn

2nd Pi - after restartdns on 1st Pi & 2nd Pi (before no transmission was possible)
https://tricorder.pi-hole.net/wy1cqzrbsn

I will deactivate gravity-sync in the meantime. Maybe there is something to be found in the logs that does not point to gravity-sync, but just to be safe, I will deactivate it.

**Comment by DL6ER** [comment]
@BlackScreen Thanks for trying to disable gravity-sync. Does it have logging itself? Maybe this includes why it doesn't restart FTL...

Your first log just shows
```
[✗] pihole-FTL daemon is inactive
```
```
   [2021-04-24 10:00:11.379 17235M] Shutting down...
[...]
   [2021-04-24 10:00:11.750 17235M] ########## FTL terminated after 23h 52m 11s  (code 0)! ##########
```
which is again remarkably close to a full hour so very likely caused by a `cron` job.

Your second log shows it is running fine about four minutes later:
```
[✓] pihole-FTL daemon is active
```
```
[2021-04-24 10:04:33.794 26793M] PID of FTL process: 26793
```

**Comment by BlackScreen** [comment]
I checked the log file and this are the entries in the time span relevant to this issue:

```
Di 20. Apr 07:19:13 CEST 2021 [SMART]
Di 20. Apr 09:31:10 CEST 2021 [SMART]
Mi 21. Apr 23:44:08 CEST 2021 [SMART]
Mi 21. Apr 23:45:13 CEST 2021 [SMART]
Do 22. Apr 03:00:01 CEST 2021 [BACKUP]
Sa 24. Apr 03:00:02 CEST 2021 [BACKUP]
```

So it seems, that gravity-sync did nothing on that side, during the relevant time period. Weird.
You are right with the suspected cron job, any idea where to look further if that was the case?
Maybe gravity-sync was the cause, maybe not. We will see.

**Comment by DL6ER** [comment]
> So it seems, that gravity-sync did nothing on that side, during the relevant time period. Weird.

I wouldn't say this. My *assumption* at this point is that it failed in the middle of the process (after stopping/before starting FTL). If logging only happens at the end, it'd have never logged anything here.

**Comment by BlackScreen** [comment]
It happened again at 10 am. With deactivated gravity-sync and no cron job that was created by me at that time.
Here is the log: 
https://tricorder.pi-hole.net/7xq7kjw64b

Maybe I have to reset the whole Pi and build it from scratch or is there any log file that can lead me go the cause?

**Comment by DL6ER** [comment]
@BlackScreen Please check `/etc/cron.d` `/etc/cron.daily`, `/etc/crontab` and friends for something running at 10 am.
