### ISSUE TITLE
After uptating Pi-Hole to v6 on Synoloy NAS it does not work anymore - getrandom() failed in generate_password()

### ISSUE THREAD

**Issue by G-3-3-R-T** [pi-hole/FTL#2245]
### Versions

DiskStation:/# pihole -v
Core version is v6.0.3 (Latest: v6.0.3)
Web version is v6.0.1 (Latest: v6.0.1)
FTL version is v6.0.2 (Latest: v6.0.2)

### Platform
- OS and version: Linux version 3.10.108 (root@build7) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Mar 24 00:28:41 CST 2023

- Platform:  Synology NAS DS1517+ / INTEL Atom C2538 x86

### Actual behavior / bug

Since updating to v6 it stops and exit, in the log there are two errors.

 ```
2025-02-21 20:08:00.655 UTC [58M] ERROR: getrandom() failed in generate_password()
 2025-02-21 20:08:00.655 UTC [58M] ERROR: Failed to generate CLI password hash
```

### Steps to reproduce

This is the Portainer compose I use:

```
services:
  pihole:
    image: pihole/pihole
    container_name: pi-hole
    network_mode: host
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
    environment:
      TZ: Europe/Brussels
      FTLCONF_webserver_api_password: pihole
      FTLCONF_webserver_port: 8181
      FTLCONF_debug_api: 'true'
      DNSMASQ_USER: root # root is required for Synology NAS'ses
      PIHOLE_UID: 1027
      PIHOLE_GID: 101
    cap_add:
      - SYS_TIME
      - SYS_NICE
```

## WORKAROUND

When leaving the password empty at `FTLCONF_webserver_api_password:` Pi-Hole will work.

**Comment by DL6ER** [comment]
Could you please try
```
sudo pihole checkout ftl development
```
to see if this improves on the situation?

**Comment by mrmuiz** [comment]
> pihole checkout ftl development

![Image](https://github.com/user-attachments/assets/d11c93fc-c8c1-4e66-bd3e-29b592c380bd)

**Comment by yubiuser** [comment]
For docker, you would need to build a custom image with that branch.
https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#building-the-image-locally

`./build.sh -f development`

**Comment by M4ndaL0re** [comment]
same here on Synology
> <html><body>

2025/02/22 19:49:02 | stdout | FTL version is v6.0.2 (Latest: v6.0.2)
-- | -- | --
2025/02/22 19:49:02 | stdout | Web version is v6.0.1 (Latest: v6.0.1)
2025/02/22 19:49:02 | stdout | Core version is v6.0.3 (Latest: v6.0.3)


</body>
</html>

> 
```

> <html><body>
> <!--StartFragment-->
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.149 CET [55M] INFO: ########## FTL terminated after 3m 32s  (code 0)! ##########
> -- | -- | --
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: PID file emptied
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: All threads joined
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Thread ntp-client (4) is idle, terminating it.
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Thread timer (3) is idle, terminating it.
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Thread dns-client (2) is idle, terminating it.
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Thread housekeeper (1) is idle, terminating it.
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Thread database (0) is idle, terminating it.
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Waiting for threads to join
> 2025/02/22 19:48:37 | stdout | 2025-02-22 19:48:37.038 CET [55M] INFO: Finished final database update
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.341 CET [55/T239] INFO: Stored 0 API sessions in the database
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.340 CET [55/T239] INFO: PID file emptied
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.336 CET [55/T239] INFO: All threads joined
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.336 CET [55/T239] INFO: Thread ntp-client (4) is idle, terminating it.
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.336 CET [55/T239] INFO: Thread timer (3) is idle, terminating it.
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.336 CET [55/T239] INFO: Thread dns-client (2) is idle, terminating it.
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.336 CET [55/T239] INFO: Thread housekeeper (1) is idle, terminating it.
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.336 CET [55/T239] INFO: Thread database (0) is idle, terminating it.
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.335 CET [55/T239] INFO: Waiting for threads to join
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.335 CET [55/T239] INFO: Thank you for helping us to improve our FTL engine!
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.335 CET [55/T239] INFO: Please also include some lines from above the !!!!!!!!! header.
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.335 CET [55/T239] INFO: ---------------------------------------------------
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.335 CET [55/T239] INFO: rw------- root:root        88   FTL-55-lock
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.335 CET [55/T239] INFO: rw------- root:root       328   FTL-55-counters
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.334 CET [55/T239] INFO: rw------- root:root       144   FTL-55-settings
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.334 CET [55/T239] INFO: rw------- root:root        82K  FTL-55-strings
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.334 CET [55/T239] INFO: rw------- root:root         8K  FTL-55-domains
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.334 CET [55/T239] INFO: rw------- root:root       348K  FTL-55-clients
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.334 CET [55/T239] INFO: rw------- root:root        29K  FTL-55-upstreams
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.333 CET [55/T239] INFO: rw------- root:root         1M  FTL-55-queries
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.333 CET [55/T239] INFO: rw------- root:root         8K  FTL-55-overTime
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.333 CET [55/T239] INFO: rw------- root:root        20K  FTL-55-dns-cache
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.333 CET [55/T239] INFO: rw------- root:root         4K  FTL-55-per-client-regex
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.333 CET [55/T239] INFO: rw------- root:root       569K  FTL-55-fifo-log
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.332 CET [55/T239] INFO: rw------- root:root         4K  FTL-55-clients-lookup
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.332 CET [55/T239] INFO: rw------- root:root         4K  FTL-55-domains-lookup
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.332 CET [55/T239] INFO: rw------- root:root         4K  FTL-55-dns-cache-lookup
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.332 CET [55/T239] INFO: rw------- root:root       786K  FTL-55-recycler
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.332 CET [55/T239] INFO: rwxr-xr-x root:root        14K  ..
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.332 CET [55/T239] INFO: rwxrwxrwx root:root       360   .
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO: File Mode User:Group      Size  Filename
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO: ------ Listing content of directory /dev/shm ------
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO: !!! INFO: pihole-FTL has not been compiled with glibc/backtrace support, not generating one !!!
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO:      with code:  SEGV_MAPERR (Address not mapped to object)
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO:      at address: 0
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO: Received signal: Segmentation fault
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO:                  Name: civetweb-worker
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO:                  TID: 239
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO:                  PID: 55
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO: Process details: MID: 55
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.331 CET [55/T239] INFO: Compiled for linux/amd64 (compiled on CI) using cc (Alpine 14.2.0) 14.2.0
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: FTL user: started as root, ended as root
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: FTL date: 2025-02-21 21:48:20 +0000
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: FTL commit: ac500d5f
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: FTL version: v6.0.2
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: FTL branch: master
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: FTL has been running for 195 seconds
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: and include in your report already the following details:
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: Please report a bug at https://github.com/pi-hole/FTL/issues
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.330 CET [55/T239] INFO: ---------------------------->  FTL crashed!  <----------------------------
> 2025/02/22 19:48:19 | stdout | 2025-02-22 19:48:19.329 CET [55/T239] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> <!--EndFragment-->
> </body>
> </html>
```

![Image](https://github.com/user-attachments/assets/815485e4-d2f6-4dcd-a85e-a790e50d7d75)

**Comment by G-3-3-R-T** [comment]
Complete log from startup to exit:

```
  [i] Setting up user & group for the pihole user
  [i] ID for user pihole is already 1027, no need to change
  [i] ID for group pihole is already 101, no need to change

  [i] Starting FTL configuration
  [i] Assigning password defined by Environment Variable
  [i] Starting crond for scheduled scripts. Randomizing times for gravity and update checker

  [i] Ensuring logrotate script exists in /etc/pihole

  [i] Gravity migration checks
  [i] Existing gravity database found - schema will be upgraded if necessary
     

  [i] pihole-FTL pre-start checks
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
        * CAP_SYS_NICE
        * CAP_SYS_TIME
Failed to set capabilities on file '/usr/bin/pihole-FTL': Not supported

  [i] Starting pihole-FTL (no-daemon) as root

  [i] Version info:
      Core version is v6.0.4 (Latest: v6.0.4)
      Web version is v6.0.1 (Latest: v6.0.1)
      FTL version is v6.0.2 (Latest: v6.0.2)

2025-02-24 21:44:00.349 UTC [54M] INFO: ########## FTL started on DiskStation2! ##########
2025-02-24 21:44:00.349 UTC [54M] INFO: FTL branch: master
2025-02-24 21:44:00.350 UTC [54M] INFO: FTL version: v6.0.2
2025-02-24 21:44:00.350 UTC [54M] INFO: FTL commit: ac500d5f
2025-02-24 21:44:00.350 UTC [54M] INFO: FTL date: 2025-02-21 21:48:20 +0000
2025-02-24 21:44:00.350 UTC [54M] INFO: FTL user: root
2025-02-24 21:44:00.350 UTC [54M] INFO: Compiled for linux/amd64 (compiled on CI) using cc (Alpine 14.2.0) 14.2.0
2025-02-24 21:44:00.353 UTC [54M] ERROR: getrandom() failed in create_password()
2025-02-24 21:44:00.353 UTC [54M] DEBUG_ANY: ************************
2025-02-24 21:44:00.353 UTC [54M] DEBUG_ANY: *    DEBUG SETTINGS    *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * DATABASE:       NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * NETWORKING:     NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * LOCKS:          NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * QUERIES:        NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * FLAGS:          NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * SHMEM:          NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * GC:             NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * ARP:            NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * REGEX:          NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * API:            YES  *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * TLS:            NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * OVERTIME:       NO   *
2025-02-24 21:44:00.354 UTC [54M] DEBUG_ANY: * STATUS:         NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * CAPS:           NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * DNSSEC:         NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * VECTORS:        NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * RESOLVER:       NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * EDNS0:          NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * CLIENTS:        NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * ALIASCLIENTS:   NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * EVENTS:         NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * HELPER:         NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * CONFIG:         NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * INOTIFY:        NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * WEBSERVER:      NO   *
2025-02-24 21:44:00.355 UTC [54M] DEBUG_ANY: * EXTRA:          NO   *
2025-02-24 21:44:00.356 UTC [54M] DEBUG_ANY: * RESERVED:       NO   *
2025-02-24 21:44:00.356 UTC [54M] DEBUG_ANY: * NTP:            NO   *
2025-02-24 21:44:00.356 UTC [54M] DEBUG_ANY: * NETLINK:        NO   *
2025-02-24 21:44:00.356 UTC [54M] DEBUG_ANY: ************************
2025-02-24 21:44:00.356 UTC [54M] INFO: 3 FTLCONF environment variables found (3 used, 0 invalid, 0 ignored)
2025-02-24 21:44:00.356 UTC [54M] INFO:    [✓] FTLCONF_debug_api is used
2025-02-24 21:44:00.356 UTC [54M] INFO:    [✓] FTLCONF_webserver_api_password is used
2025-02-24 21:44:00.356 UTC [54M] INFO:    [✓] FTLCONF_webserver_port is used
2025-02-24 21:44:00.358 UTC [54M] ERROR: Trying to compare a NULL (L) string in writeFTLtoml() (/app/src/config/toml_writer.c:105)
2025-02-24 21:44:00.359 UTC [54M] INFO: Wrote config file:
2025-02-24 21:44:00.359 UTC [54M] INFO:  - 152 total entries
2025-02-24 21:44:00.359 UTC [54M] INFO:  - 147 entries are default
2025-02-24 21:44:00.359 UTC [54M] INFO:  - 5 entries are modified
2025-02-24 21:44:00.359 UTC [54M] INFO:  - 2 entries are forced through environment
2025-02-24 21:44:00.362 UTC [54M] INFO: Parsed config file /etc/pihole/pihole.toml successfully
2025-02-24 21:44:00.363 UTC [54M] INFO: PID file does not exist or not readable
2025-02-24 21:44:00.363 UTC [54M] INFO: No other running FTL process found.
2025-02-24 21:44:00.366 UTC [54M] WARNING: Starting pihole-FTL as user root is not recommended
2025-02-24 21:44:00.366 UTC [54M] INFO: PID of FTL process: 54
2025-02-24 21:44:00.367 UTC [54M] INFO: listening on 0.0.0.0 port 53
2025-02-24 21:44:00.367 UTC [54M] INFO: listening on :: port 53
2025-02-24 21:44:00.384 UTC [54M] INFO: PID of FTL process: 54
2025-02-24 21:44:00.386 UTC [54M] INFO: Database version is 21
2025-02-24 21:44:00.387 UTC [54M] INFO: Database successfully initialized
2025-02-24 21:44:00.404 UTC [54M] INFO: Imported 25 queries from the on-disk database (it has 126 rows)
2025-02-24 21:44:00.404 UTC [54M] INFO: Parsing queries in database
2025-02-24 21:44:00.410 UTC [54M] INFO: Imported 25 queries from the long-term database
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Total DNS queries: 25
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Cached DNS queries: 25
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Forwarded DNS queries: 0
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Blocked DNS queries: 0
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Unknown DNS queries: 0
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Unique domains: 1
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Unique clients: 1
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> DNS cache records: 0
2025-02-24 21:44:00.410 UTC [54M] INFO:  -> Known forward destinations: 0
2025-02-24 21:44:00.830 UTC [54M] INFO: FTL is running as root
2025-02-24 21:44:00.831 UTC [54M] INFO: Web server ports:
2025-02-24 21:44:00.831 UTC [54M] INFO:   - 8181 (HTTP, IPv4)
2025-02-24 21:44:00.831 UTC [54M] DEBUG_API: Redirecting /admin$ --308--> /admin/
2025-02-24 21:44:00.831 UTC [54M] DEBUG_API: Login URI: /admin/login
2025-02-24 21:44:00.831 UTC [54M] DEBUG_API: Admin API URI: /admin/api
2025-02-24 21:44:00.831 UTC [54M] INFO: Restored 0 API sessions from the database
2025-02-24 21:44:00.849 UTC [54M] ERROR: getrandom() failed in generate_password()
2025-02-24 21:44:00.850 UTC [54M] ERROR: Failed to generate CLI password hash!
2025-02-24 21:44:00.851 UTC [54M] INFO: Blocking status is enabled
2025-02-24 21:44:00.954 UTC [54/T92] INFO: Compiled 0 allow and 0 deny regex for 1 client in 0.3 msec
2025-02-24 21:44:04.961 UTC [54/T91] INFO: Received 8/8 valid NTP replies from pool.ntp.org
2025-02-24 21:44:04.961 UTC [54/T91] INFO: Time offset: -1.561046e+00 ms (excluded 0 outliers)
2025-02-24 21:44:04.961 UTC [54/T91] INFO: Round-trip delay: 1.401567e+01 ms (excluded 0 outliers)
2025-02-24 21:44:04.961 UTC [54/T174] INFO: NTP server listening on 0.0.0.0:123 (IPv4)
2025-02-24 21:44:04.961 UTC [54/T175] INFO: NTP server listening on :::123 (IPv6)
2025-02-24 21:45:00.127 UTC [54M] DEBUG_ANY: dnsmasq received signal 17
2025-02-24 21:45:00.141 UTC [54M] DEBUG_ANY: dnsmasq received signal 17
2025-02-24 21:45:24.549 UTC [54/T197] INFO: Local URI: "/admin/"
2025-02-24 21:45:24.549 UTC [54/T197] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2025-02-24 21:45:24.549 UTC [54/T197] INFO: ---------------------------->  FTL crashed!  <----------------------------
2025-02-24 21:45:24.549 UTC [54/T197] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2025-02-24 21:45:24.549 UTC [54/T197] INFO: Please report a bug at https://github.com/pi-hole/FTL/issues
2025-02-24 21:45:24.549 UTC [54/T197] INFO: and include in your report already the following details:
2025-02-24 21:45:24.549 UTC [54/T197] INFO: FTL has been running for 84 seconds
2025-02-24 21:45:24.549 UTC [54/T197] INFO: FTL branch: master
2025-02-24 21:45:24.549 UTC [54/T197] INFO: FTL version: v6.0.2
2025-02-24 21:45:24.549 UTC [54/T197] INFO: FTL commit: ac500d5f
2025-02-24 21:45:24.549 UTC [54/T197] INFO: FTL date: 2025-02-21 21:48:20 +0000
2025-02-24 21:45:24.550 UTC [54/T197] INFO: FTL user: started as root, ended as root
2025-02-24 21:45:24.550 UTC [54/T197] INFO: Compiled for linux/amd64 (compiled on CI) using cc (Alpine 14.2.0) 14.2.0
2025-02-24 21:45:24.550 UTC [54/T197] INFO: Process details: MID: 54
2025-02-24 21:45:24.550 UTC [54/T197] INFO:                  PID: 54
2025-02-24 21:45:24.550 UTC [54/T197] INFO:                  TID: 197
2025-02-24 21:45:24.550 UTC [54/T197] INFO:                  Name: civetweb-worker
2025-02-24 21:45:24.550 UTC [54/T197] INFO: Received signal: Segmentation fault
2025-02-24 21:45:24.550 UTC [54/T197] INFO:      at address: 0
2025-02-24 21:45:24.550 UTC [54/T197] INFO:      with code:  SEGV_MAPERR (Address not mapped to object)
2025-02-24 21:45:24.550 UTC [54/T197] INFO: !!! INFO: pihole-FTL has not been compiled with glibc/backtrace support, not generating one !!!
2025-02-24 21:45:24.550 UTC [54/T197] INFO: ------ Listing content of directory /dev/shm ------
2025-02-24 21:45:24.550 UTC [54/T197] INFO: File Mode User:Group      Size  Filename
2025-02-24 21:45:24.550 UTC [54/T197] INFO: rwxrwxrwx root:root       360   .
2025-02-24 21:45:24.550 UTC [54/T197] INFO: rwxr-xr-x root:root       340   ..
2025-02-24 21:45:24.550 UTC [54/T197] INFO: rw------- root:root       786K  FTL-54-recycler
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root         4K  FTL-54-dns-cache-lookup
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root         4K  FTL-54-domains-lookup
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root         4K  FTL-54-clients-lookup
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root       569K  FTL-54-fifo-log
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root         4K  FTL-54-per-client-regex
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root        20K  FTL-54-dns-cache
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root         8K  FTL-54-overTime
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root       295K  FTL-54-queries
2025-02-24 21:45:24.551 UTC [54/T197] INFO: rw------- root:root        29K  FTL-54-upstreams
2025-02-24 21:45:24.552 UTC [54/T197] INFO: rw------- root:root       348K  FTL-54-clients
2025-02-24 21:45:24.552 UTC [54/T197] INFO: rw------- root:root         4K  FTL-54-domains
2025-02-24 21:45:24.552 UTC [54/T197] INFO: rw------- root:root        82K  FTL-54-strings
2025-02-24 21:45:24.552 UTC [54/T197] INFO: rw------- root:root       144   FTL-54-settings
2025-02-24 21:45:24.552 UTC [54/T197] INFO: rw------- root:root       328   FTL-54-counters
2025-02-24 21:45:24.552 UTC [54/T197] INFO: rw------- root:root        88   FTL-54-lock
2025-02-24 21:45:24.552 UTC [54/T197] INFO: ---------------------------------------------------
2025-02-24 21:45:24.552 UTC [54/T197] INFO: Please also include some lines from above the !!!!!!!!! header.
2025-02-24 21:45:24.552 UTC [54/T197] INFO: Thank you for helping us to improve our FTL engine!
2025-02-24 21:45:24.552 UTC [54/T197] INFO: Waiting for threads to join
2025-02-24 21:45:24.552 UTC [54/T197] INFO: Thread database (0) is idle, terminating it.
2025-02-24 21:45:24.552 UTC [54/T197] INFO: Thread housekeeper (1) is idle, terminating it.
2025-02-24 21:45:24.552 UTC [54/T197] INFO: Thread dns-client (2) is idle, terminating it.
2025-02-24 21:45:24.553 UTC [54/T197] INFO: Thread timer (3) is idle, terminating it.
2025-02-24 21:45:24.553 UTC [54/T197] INFO: Thread ntp-client (4) is idle, terminating it.
2025-02-24 21:45:24.553 UTC [54/T197] INFO: All threads joined
2025-02-24 21:45:24.553 UTC [54/T197] DEBUG_ANY: Closing gravity database
2025-02-24 21:45:24.553 UTC [54/T197] INFO: PID file emptied
2025-02-24 21:45:24.554 UTC [54/T197] INFO: Stored 0 API sessions in the database
2025-02-24 21:45:25.747 UTC [54M] DEBUG_ANY: Shutting down... // exit code 0 // jmpret 0
2025-02-24 21:45:25.998 UTC [54M] INFO: Finished final database update
2025-02-24 21:45:25.998 UTC [54M] INFO: Waiting for threads to join
2025-02-24 21:45:25.998 UTC [54M] INFO: Thread database (0) is idle, terminating it.
2025-02-24 21:45:25.998 UTC [54M] INFO: Thread housekeeper (1) is idle, terminating it.
2025-02-24 21:45:25.998 UTC [54M] INFO: Thread dns-client (2) is idle, terminating it.
2025-02-24 21:45:25.999 UTC [54M] INFO: Thread timer (3) is idle, terminating it.
2025-02-24 21:45:25.999 UTC [54M] INFO: Thread ntp-client (4) is idle, terminating it.
2025-02-24 21:45:25.999 UTC [54M] INFO: All threads joined
2025-02-24 21:45:25.999 UTC [54M] INFO: PID file emptied
2025-02-24 21:45:25.999 UTC [54M] DEBUG_API: CLI password removed
2025-02-24 21:45:26.107 UTC [54M] INFO: ########## FTL terminated after 1m 25s  (code 0)! ##########

  [i] pihole-FTL exited with status 0
```

**Comment by yubiuser** [comment]
@G-3-3-R-T 

Did you build the image locally using then command above? Because then container still uses FTL's master branch

```
2025-02-24 21:44:00.349 UTC [54M] INFO: FTL branch: master
```

**Comment by G-3-3-R-T** [comment]
Same issue, when password is set at `FTLCONF_webserver_api_password:` Pi-Hole will not work.

This is the FTL branch: development

```
  [i] Setting up user & group for the pihole user
  [i] ID for user pihole is already 1027, no need to change
  [i] ID for group pihole is already 101, no need to change

  [i] Starting FTL configuration
  [i] Assigning password defined by Environment Variable
  [i] Starting crond for scheduled scripts. Randomizing times for gravity and update checker

  [i] Ensuring logrotate script exists in /etc/pihole

  [i] Gravity migration checks
  [i] Existing gravity database found - schema will be upgraded if necessary
     

  [i] pihole-FTL pre-start checks
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
        * CAP_SYS_NICE
        * CAP_SYS_TIME
Failed to set capabilities on file '/usr/bin/pihole-FTL': Not supported

  [i] Starting pihole-FTL (no-daemon) as root

  [i] Version info:
      Core
          Version is 9840b42 (Latest: null)
          Branch is development
          Hash is 9840b428 (Latest: c5d66c21)
      Web
          Version is d3d32e3 (Latest: null)
          Branch is development
          Hash is d3d32e31 (Latest: 3ecc3e7d)
      FTL
          Version is vDev-45d0c8a (Latest: null)
          Branch is development
          Hash is 45d0c8af (Latest: 0c9a3cd0)

2025-02-28 12:55:18.799 UTC [54M] INFO: ########## FTL started on DiskStation2! ##########
2025-02-28 12:55:18.799 UTC [54M] INFO: FTL branch: development
2025-02-28 12:55:18.799 UTC [54M] INFO: FTL version: vDev-45d0c8a
2025-02-28 12:55:18.799 UTC [54M] INFO: FTL commit: 45d0c8af
2025-02-28 12:55:18.799 UTC [54M] INFO: FTL date: 2025-02-24 09:00:44 +0100
2025-02-28 12:55:18.799 UTC [54M] INFO: FTL user: root
2025-02-28 12:55:18.799 UTC [54M] INFO: Compiled for linux/amd64 (compiled on CI) using cc (Alpine 14.2.0) 14.2.0
2025-02-28 12:55:18.802 UTC [54M] ERROR: getrandom() failed in get_secure_randomness(): Function not implemented
2025-02-28 12:55:18.802 UTC [54M] DEBUG_ANY: ************************
2025-02-28 12:55:18.802 UTC [54M] DEBUG_ANY: *    DEBUG SETTINGS    *
2025-02-28 12:55:18.802 UTC [54M] DEBUG_ANY: * DATABASE:       NO   *
2025-02-28 12:55:18.802 UTC [54M] DEBUG_ANY: * NETWORKING:     NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * LOCKS:          NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * QUERIES:        NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * FLAGS:          NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * SHMEM:          NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * GC:             NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * ARP:            NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * REGEX:          NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * API:            YES  *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * TLS:            NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * OVERTIME:       NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * STATUS:         NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * CAPS:           NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * DNSSEC:         NO   *
2025-02-28 12:55:18.803 UTC [54M] DEBUG_ANY: * VECTORS:        NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * RESOLVER:       NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * EDNS0:          NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * CLIENTS:        NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * ALIASCLIENTS:   NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * EVENTS:         NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * HELPER:         NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * CONFIG:         NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * INOTIFY:        NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * WEBSERVER:      NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * EXTRA:          NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * RESERVED:       NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * NTP:            NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: * NETLINK:        NO   *
2025-02-28 12:55:18.804 UTC [54M] DEBUG_ANY: ************************
2025-02-28 12:55:18.805 UTC [54M] INFO: 3 FTLCONF environment variables found (3 used, 0 invalid, 0 ignored)
2025-02-28 12:55:18.805 UTC [54M] INFO:    [✓] FTLCONF_debug_api is used
2025-02-28 12:55:18.805 UTC [54M] INFO:    [✓] FTLCONF_webserver_api_password is used
2025-02-28 12:55:18.805 UTC [54M] INFO:    [✓] FTLCONF_webserver_port is used
2025-02-28 12:55:18.806 UTC [54M] ERROR: Trying to compare a NULL (L) string in writeFTLtoml() (/app/src/config/toml_writer.c:105)
2025-02-28 12:55:18.809 UTC [54M] INFO: Wrote config file:
2025-02-28 12:55:18.809 UTC [54M] INFO:  - 153 total entries
2025-02-28 12:55:18.809 UTC [54M] INFO:  - 148 entries are default
2025-02-28 12:55:18.809 UTC [54M] INFO:  - 5 entries are modified
2025-02-28 12:55:18.809 UTC [54M] INFO:  - 2 entries are forced through environment
2025-02-28 12:55:18.812 UTC [54M] INFO: Parsed config file /etc/pihole/pihole.toml successfully
2025-02-28 12:55:18.812 UTC [54M] INFO: PID file does not exist or not readable
2025-02-28 12:55:18.812 UTC [54M] INFO: No other running FTL process found.
2025-02-28 12:55:18.815 UTC [54M] WARNING: Starting pihole-FTL as user root is not recommended
2025-02-28 12:55:18.815 UTC [54M] INFO: PID of FTL process: 54
2025-02-28 12:55:18.816 UTC [54M] INFO: listening on 0.0.0.0 port 53
2025-02-28 12:55:18.816 UTC [54M] INFO: listening on :: port 53
2025-02-28 12:55:18.818 UTC [54M] INFO: PID of FTL process: 54
2025-02-28 12:55:18.819 UTC [54M] INFO: Database version is 21
2025-02-28 12:55:18.820 UTC [54M] INFO: Database successfully initialized
2025-02-28 12:55:18.827 UTC [54M] INFO: Imported 25 queries from the on-disk database (it has 197 rows)
2025-02-28 12:55:18.827 UTC [54M] INFO: Parsing queries in database
2025-02-28 12:55:18.829 UTC [54M] INFO: Imported 25 queries from the long-term database
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Total DNS queries: 25
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Cached DNS queries: 25
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Forwarded DNS queries: 0
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Blocked DNS queries: 0
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Unknown DNS queries: 0
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Unique domains: 1
2025-02-28 12:55:18.829 UTC [54M] INFO:  -> Unique clients: 1
2025-02-28 12:55:18.830 UTC [54M] INFO:  -> DNS cache records: 0
2025-02-28 12:55:18.830 UTC [54M] INFO:  -> Known forward destinations: 0
2025-02-28 12:55:19.501 UTC [54M] INFO: FTL is running as root
2025-02-28 12:55:19.502 UTC [54M] INFO: Web server ports:
2025-02-28 12:55:19.502 UTC [54M] INFO:   - 0.0.0.0:8181 (HTTP, IPv4)
2025-02-28 12:55:19.502 UTC [54M] DEBUG_API: Redirecting /admin$ --308--> /admin/
2025-02-28 12:55:19.502 UTC [54M] DEBUG_API: Login URI: /admin/login
2025-02-28 12:55:19.502 UTC [54M] DEBUG_API: Admin API URI: /admin/api
2025-02-28 12:55:19.502 UTC [54M] INFO: Restored 0 API sessions from the database
2025-02-28 12:55:19.505 UTC [54M] ERROR: getrandom() failed in get_secure_randomness(): Function not implemented
2025-02-28 12:55:19.506 UTC [54M] ERROR: Failed to generate CLI password hash!
2025-02-28 12:55:19.507 UTC [54M] INFO: Blocking status is enabled
2025-02-28 12:55:19.610 UTC [54/T90] INFO: Compiled 0 allow and 0 deny regex for 1 client in 0.4 msec
2025-02-28 12:55:23.631 UTC [54/T89] INFO: Received 8/8 valid NTP replies from pool.ntp.org
2025-02-28 12:55:23.631 UTC [54/T89] INFO: Time offset: 1.271099e+00 ms (excluded 0 outliers)
2025-02-28 12:55:23.631 UTC [54/T89] INFO: Round-trip delay: 1.418859e+01 ms (excluded 0 outliers)
2025-02-28 12:55:23.631 UTC [54/T166] INFO: NTP server listening on 0.0.0.0:123 (IPv4)
2025-02-28 12:55:23.631 UTC [54/T167] INFO: NTP server listening on :::123 (IPv6)
2025-02-28 12:56:00.112 UTC [54M] DEBUG_ANY: dnsmasq received signal 17
2025-02-28 12:56:00.119 UTC [54M] DEBUG_ANY: dnsmasq received signal 17
2025-02-28 12:56:41.011 UTC [54/T190] DEBUG_API: Local URI: "/admin/"
2025-02-28 12:56:41.012 UTC [54/T190] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2025-02-28 12:56:41.012 UTC [54/T190] INFO: ---------------------------->  FTL crashed!  <----------------------------
2025-02-28 12:56:41.012 UTC [54/T190] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2025-02-28 12:56:41.012 UTC [54/T190] INFO: Please report a bug at https://github.com/pi-hole/FTL/issues
2025-02-28 12:56:41.012 UTC [54/T190] INFO: and include in your report already the following details:
2025-02-28 12:56:41.012 UTC [54/T190] INFO: FTL has been running for 83 seconds
2025-02-28 12:56:41.012 UTC [54/T190] INFO: FTL branch: development
2025-02-28 12:56:41.012 UTC [54/T190] INFO: FTL version: vDev-45d0c8a
2025-02-28 12:56:41.012 UTC [54/T190] INFO: FTL commit: 45d0c8af
2025-02-28 12:56:41.012 UTC [54/T190] INFO: FTL date: 2025-02-24 09:00:44 +0100
2025-02-28 12:56:41.012 UTC [54/T190] INFO: FTL user: started as root, ended as root
2025-02-28 12:56:41.012 UTC [54/T190] INFO: Compiled for linux/amd64 (compiled on CI) using cc (Alpine 14.2.0) 14.2.0
2025-02-28 12:56:41.012 UTC [54/T190] INFO: Process details: MID: 54
2025-02-28 12:56:41.012 UTC [54/T190] INFO:                  PID: 54
2025-02-28 12:56:41.012 UTC [54/T190] INFO:                  TID: 190
2025-02-28 12:56:41.012 UTC [54/T190] INFO:                  Name: civetweb-worker
2025-02-28 12:56:41.013 UTC [54/T190] INFO: Received signal: Segmentation fault
2025-02-28 12:56:41.013 UTC [54/T190] INFO:      at address: 0
2025-02-28 12:56:41.013 UTC [54/T190] INFO:      with code:  SEGV_MAPERR (Address not mapped to object)
2025-02-28 12:56:41.013 UTC [54/T190] INFO: !!! INFO: pihole-FTL has not been compiled with glibc/backtrace support, not generating one !!!
2025-02-28 12:56:41.013 UTC [54/T190] INFO: ------ Listing content of directory /dev/shm ------
2025-02-28 12:56:41.013 UTC [54/T190] INFO: File Mode User:Group      Size  Filename
2025-02-28 12:56:41.013 UTC [54/T190] INFO: rwxrwxrwx root:root       360   .
2025-02-28 12:56:41.013 UTC [54/T190] INFO: rwxr-xr-x root:root       340   ..
2025-02-28 12:56:41.013 UTC [54/T190] INFO: rw------- root:root       786K  FTL-54-recycler
2025-02-28 12:56:41.013 UTC [54/T190] INFO: rw------- root:root         4K  FTL-54-dns-cache-lookup
2025-02-28 12:56:41.013 UTC [54/T190] INFO: rw------- root:root         4K  FTL-54-domains-lookup
2025-02-28 12:56:41.013 UTC [54/T190] INFO: rw------- root:root         4K  FTL-54-clients-lookup
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root       569K  FTL-54-fifo-log
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root         4K  FTL-54-per-client-regex
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root        20K  FTL-54-dns-cache
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root         8K  FTL-54-overTime
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root       295K  FTL-54-queries
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root        29K  FTL-54-upstreams
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root       348K  FTL-54-clients
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root         4K  FTL-54-domains
2025-02-28 12:56:41.014 UTC [54/T190] INFO: rw------- root:root        82K  FTL-54-strings
2025-02-28 12:56:41.015 UTC [54/T190] INFO: rw------- root:root       144   FTL-54-settings
2025-02-28 12:56:41.015 UTC [54/T190] INFO: rw------- root:root       328   FTL-54-counters
2025-02-28 12:56:41.015 UTC [54/T190] INFO: rw------- root:root        88   FTL-54-lock
2025-02-28 12:56:41.015 UTC [54/T190] INFO: ---------------------------------------------------
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Please also include some lines from above the !!!!!!!!! header.
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Thank you for helping us to improve our FTL engine!
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Waiting for threads to join
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Thread database (0) is idle, terminating it.
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Thread housekeeper (1) is idle, terminating it.
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Thread dns-client (2) is idle, terminating it.
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Thread timer (3) is idle, terminating it.
2025-02-28 12:56:41.015 UTC [54/T190] INFO: Thread ntp-client (4) is idle, terminating it.
2025-02-28 12:56:41.015 UTC [54/T190] INFO: All threads joined
2025-02-28 12:56:41.015 UTC [54/T190] DEBUG_ANY: Closing gravity database
2025-02-28 12:56:41.016 UTC [54/T190] INFO: PID file emptied
2025-02-28 12:56:41.017 UTC [54/T190] INFO: Stored 0 API sessions in the database
2025-02-28 12:56:49.094 UTC [54M] DEBUG_ANY: Shutting down... // exit code 0 // jmpret 0
2025-02-28 12:56:49.345 UTC [54M] INFO: Finished final database update
2025-02-28 12:56:49.345 UTC [54M] INFO: Waiting for threads to join
2025-02-28 12:56:49.345 UTC [54M] INFO: Thread database (0) is idle, terminating it.
2025-02-28 12:56:49.345 UTC [54M] INFO: Thread housekeeper (1) is idle, terminating it.
2025-02-28 12:56:49.345 UTC [54M] INFO: Thread dns-client (2) is idle, terminating it.
2025-02-28 12:56:49.345 UTC [54M] INFO: Thread timer (3) is idle, terminating it.
2025-02-28 12:56:49.345 UTC [54M] INFO: Thread ntp-client (4) is idle, terminating it.
2025-02-28 12:56:49.345 UTC [54M] INFO: All threads joined
2025-02-28 12:56:49.345 UTC [54M] INFO: PID file emptied
2025-02-28 12:56:49.345 UTC [54M] DEBUG_API: CLI password removed
2025-02-28 12:56:49.380 UTC [54M] INFO: ########## FTL terminated after 1m 30s  (code 0)! ##########

  [i] pihole-FTL exited with status 0

  [i] Container will now stop or restart depending on your restart policy
      https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy
```

**Comment by PromoFaux** [comment]
This is looking more and more like an incompatibility with the Atom processor. See also:

https://github.com/pi-hole/FTL/issues/2242


@G-3-3-R-T - Just so I'm not duplicating entries in my sheet, are you also Korvo on our Discourse Forums, or do you just have a coincidentally identical system and compose file?

https://docs.google.com/spreadsheets/d/13crEk428bO87JOkIhT6xbX7MU6QQCCJONzP9xU3yxo8/edit?gid=0#gid=0

**Comment by G-3-3-R-T** [comment]
> [@G-3-3-R-T](https://github.com/G-3-3-R-T) - Just so I'm not duplicating entries in my sheet, are you also Korvo on our Discourse Forums, or do you just have a coincidentally identical system and compose file?

Yep, I'm also Korvo

**Comment by PromoFaux** [comment]
@G-3-3-R-T This should be fixed with the next release, see special tag `pihole/pihole:synology-crash`

**Comment by G-3-3-R-T** [comment]
> [@G-3-3-R-T](https://github.com/G-3-3-R-T) This should be fixed with the next release, see special tag `pihole/pihole:synology-crash`

YES the `pihole/pihole:synology-crash` do work for my Synology NAS.
No password issue anymore, great work !!

**Comment by mrmuiz** [comment]
> > [@G-3-3-R-T](https://github.com/G-3-3-R-T) This should be fixed with the next release, see special tag `pihole/pihole:synology-crash`
> 
> At the bottom screen I see this:
> 
> ```
> Docker Tag [dev-localbuild](https://github.com/pi-hole/docker-pi-hole/releases/dev-localbuild)
> Core vDev (development, 53e241f0)
> FTL vDev (fix/randomness_crash, b943517c)
> Web interface vDev (development, 3ecc3e7d)
> ```
> 
> YES the `pihole/pihole:synology-crash` do work for my Synology NAS. No password issue anymore, great work !!

I tought this was just me. 1000 reinstalls later i see this....

**Comment by mrmuiz** [comment]
![Image](https://github.com/user-attachments/assets/29a72f55-3fe6-4152-bb6b-6dc1b6a8bd03)
Still crashes into this.

**Comment by G-3-3-R-T** [comment]
> ![Image](https://github.com/user-attachments/assets/29a72f55-3fe6-4152-bb6b-6dc1b6a8bd03) Still crashes into this.

Is this also on a Synology NAS ?

**Comment by mrmuiz** [comment]
> > ![Image](https://github.com/user-attachments/assets/29a72f55-3fe6-4152-bb6b-6dc1b6a8bd03) Still crashes into this.
> 
> Is this also on a Synology NAS ?

Yes. 220+ 18gb. Latest official Docker.

**Comment by G-3-3-R-T** [comment]
> > > ! Still crashes into this.
> > 
> > 
> > Is this also on a Synology NAS ?
> 
> Yes. 220+ 18gb. Latest official Docker.

Did you use `pihole/pihole:synology-crash` ??

When using todays `pihole/pihole` when password is set `FTLCONF_webserver_api_password:` it does not crash anymore but when try to loging at loginscreen you will get `Wrong password!` error indeed.

**Comment by mrmuiz** [comment]
> > > > ! Still crashes into this.
> > > 
> > > 
> > > Is this also on a Synology NAS ?
> > 
> > 
> > Yes. 220+ 18gb. Latest official Docker.
> 
> Did you use `pihole/pihole:synology-crash` ??
> 
> When using todays `pihole/pihole` when password is set `FTLCONF_webserver_api_password:` it does not crash anymore but when try to loging at loginscreen you will get `Wrong password!` error indeed.

When i try to login a day later. Pass is gone again. Solved by using Adguard till this is fixed.

**Comment by PromoFaux** [comment]
@mrmuiz - are you using nebula-sync perchance?

**Comment by mrmuiz** [comment]
> [@mrmuiz](https://github.com/mrmuiz) - are you using nebula-sync perchance?

No.

**Comment by PromoFaux** [comment]
Hmm, OK - just wanted to check - it also wasn't clear if you had tried the `:synology-crash` tag, either. 

Regardless, the synology cash fix should now be in the latest tag.

**Comment by PromoFaux** [comment]
OK - You might be seeing something else here. The issue reported by OP should now be fixed (can you confirm @G-3-3-R-T ?)

@mrmuiz - please open a new issue describing all the symptoms that you are seeing, including your docker compose / run script and a debug log - we'll see if we can get to the bottom of it

**Comment by mrmuiz** [comment]
> OK - You might be seeing something else here. The issue reported by OP should now be fixed (can you confirm [@G-3-3-R-T](https://github.com/G-3-3-R-T) ?)
> 
> [@mrmuiz](https://github.com/mrmuiz) - please open a new issue describing all the symptoms that you are seeing, including your docker compose / run script and a debug log - we'll see if we can get to the bottom of it

Yes sir. I will as soon as i have time.

**Comment by DL6ER** [comment]
Fixed in FTL [v6.0.4](https://github.com/pi-hole/FTL/releases/tag/v6.0.4). Please all go back to `master` using
```
sudo pihole checkout ftl master
```
in case you switched to a special branch in the course of this issue. The special branch is now abandoned and won't receive updates in the future. @mrmuiz  If the issue persists even after you made sure you are on v6.0.4, feel free to creating a new issue ticket as the current one is only about randomness and has been resolved.

**Comment by G-3-3-R-T** [comment]
I can confirm that this release is working for my Synology NAS:

Docker Tag [2025.03.0](https://github.com/pi-hole/docker-pi-hole/releases/2025.03.0)
Core [v6.0.5](https://github.com/pi-hole/pi-hole/releases/v6.0.5)
FTL [v6.0.4](https://github.com/pi-hole/FTL/releases/v6.0.4)
Web interface [v6.0.2](https://github.com/pi-hole/web/releases/v6.0.2)

Thanks !

**Comment by mrmuiz** [comment]
So far so good here. 👍🏼
